### ISSUE TITLE
Open with Visual Studio Code in a new window

### ISSUE THREAD

**Issue by williambao** [franzheidl/alfred-workflows#16]
Hi,
The "Open with Visual Studio Code"  is seems replace existing window,
It is can open a folder or file in a new window?
thanks

**Comment by franzheidl** [comment]
Hi, 
how documents are being opened is the job of the application, there's nothing I can do about that I'm afraid. 
However, if one day (which I doubt) VS Code should have an Applescript/OSX Automation JS API, that could probably be done.
