### ISSUE TITLE
vscode with folder highlighted copies the folder and opens the copy

### ISSUE THREAD

**Issue by froamer** [franzheidl/alfred-workflows#18]
Hi, thanks for these great Alfred plugins!!! 

If I use vscode plugin when a folder is highlighted, the folder is copied and then Visual Studio code is opened on the copy. Is this an issue with the plugin? 

Many thanks for any help.

**Comment by franzheidl** [comment]
Hi, many thanks for your feedback.
I have tested this and I can't reproduce the behavior you describe. And I can't think of anything in the code that could possibly cause such a behavior, so I suspect it's something else outside the Alfred workflow.

**Comment by froamer** [comment]
Thanks Franz. Strange it does it consistently. I'll try it on another Mac.

**Comment by franzheidl** [comment]
Yes, please do. Let me know if you still come to the conclusion this is caused by the workflow.

**Comment by froamer** [comment]
I think I have a clue as to the cause. In terminal if I run ls -l the folders that have this behaviour have "extended attributes" indicated by the @ sign...

drwxr-xr-x@ 11 chris  staff    374 29 Jun 16:16 testfolder/

Folders that work fine look like this...

drwxr-xr-x 11 chris  staff    374 29 Jun 16:16 workingfolder/

**Comment by froamer** [comment]
Yes, I can confirm this is the cause. [This article](http://gotofritz.net/blog/geekery/os-x-extended-attibutes/) was a great help. I removed the extended attributes from the folders I commonly need to open in Visual Studio Code, but I don't know if the above helps you to avoid the issue in the plugin?

**Comment by franzheidl** [comment]
Hm. I suppose it's not the sheer fact that a folder has extended attributes that causes the behavior you describe, I suspect it is a specific of these attributes that causes this behavior.

However, the workflow uses a standard applescript command to tell an application to open a specific folder, and I'm not sure if it is in the scope of this workflow to deal with/override specific OS level behavior.

I might investigate further, but not my top priority at the moment. If you're willing to norrow down which extended attribute is the cause let me know.

**Comment by froamer** [comment]
I have a workaround (remove the extended attributes as per the article link above). Hopefully this post will help others with the same issue. Many thanks for looking into it for me. These plugins are so useful.
