### ISSUE TITLE
Any way to run it in the background?

### ISSUE THREAD

**Issue by gandalfsaxe** [franzheidl/alfred-workflows#22]

**Comment by franzheidl** [comment]
What exactly do you mean by "run in the background"? Generally speaking I am bound to how Alfred works and what it offers…

**Comment by gandalfsaxe** [comment]
Just meant the terminal command running without a terminal window showing up.

**Comment by gandalfsaxe** [comment]
I found what I was looking for here :)

https://www.alfredforum.com/topic/1550-runcommand-—-run-shell-commands-without-opening-a-terminal/
